export { default as courseOne } from "./course-one.png?responsive";
export { default as courseTwo } from "./course-two.png?responsive";
export { default as courseThree } from "./course-three.png?responsive";
export { default as courseFour } from "./course-four.png?responsive";
export { default as courseFive } from "./course-five.png?responsive";
export { default as courseSix } from "./course-six.png?responsive";
export { default as tutorBasic } from "./tutor-basic.png?responsive";
export { default as tutorSoftware } from "./tutor-software.png?responsive";
export { default as tutorDesign } from "./tutor-design.png?responsive";
