export { default as groupPics } from "./group-pics.png?lossless&responsive";
export { default as heroBgOneDesktop } from "./hero-bg-one-desktop.png?responsive";
export { default as heroBgTwoDesktop } from "./hero-bg-two-desktop.png?responsive";
export { default as heroImageDesktop } from "./hero-image-desktop.png?responsive";
export { default as logoBig } from "./logo-big.png?responsive";
export { default as sectionBg } from "./section-bg.png?responsive";
export { default as tabImageOne } from "./tab-image-one.png?responsive";
export { default as tabImageThree } from "./tab-image-three.png?responsive";
export { default as tabImageTwo } from "./tab-image-two.png?responsive";
